### ISSUE TITLE
Determine clean-ist-er integration points for cloud/AWS. 

### ISSUE THREAD

**Issue by timothysc** [heptio/eventrouter#3]
Options include:

push to log-rotates volume 
push to s3
push to some SQL
...? 

/cc @kstewart

**Comment by kstewart** [comment]
@timothysc if we're primarily concerned about AWS, pushing to S3 would be my choice. Otherwise, my conservative self would say push to a log-rotates volume. Using a SQL store makes it easier to immediately do analysis but then you run the risk of picking the "wrong" store for some people (*I want it in PostgreSQL, not MySQL!*) and end up having to support multiple which can become a burden. Just my $0.02.

**Comment by timothysc** [comment]
Currently investigating https://aws.amazon.com/cloudwatch/ integration for both log and metric data.

**Comment by timothysc** [comment]
going to close this in lieu of http://docs.heptio.com/content/tutorials/elastic.html .

**Comment by alok87** [comment]
@timothysc ES kibana setup is expensive setup with so many events getting stored. Is not it good to have s3 solution also.
